spring:
  application:
    name: MySpringAi
  #database
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: 123456
    driver-class-name: org.postgresql.Driver
  ai:
    dashscope:
      api-key: ${DASHSCOPE_API_KEY}
      chat:
        options:
          model: qwen-plus
          temperature: 0.7
      embedding:
        options:
          model: text-embedding-v3


    vectorstore:
      pgvector:
        table-name: vector_store     # ????? vector_store
        dimensions: 1024                    # ? ???? text-embedding-v3 ??????
        index-type: HNSW                    # ???HNSW ? IVFFLAT
        distance-type: COSINE_DISTANCE      # ???COSINE_DISTANCE, INNER_PRODUCT, EUCLIDEAN_DISTANCE
        max-document-batch-size: 1000



    #????????????,???????
    chat:
      memory:
        repository:
          jdbc:
            initialize-schema: always
  http:
    client:
      factory: jdk

logging:
  level:
    org.springframework.ai.chat.client.advisor.SimpleLoggerAdvisor: WARN
    com.storm: DEBUG
    #开启Spring AI 的 PgVectorStore 在执行 similaritySearch 时，
    #会记录检索到的文档（含内容和分数），只需开启日志级别。
    org.springframework.ai.vectorstore.pgvector.PgVectorStore: DEBUG
